
DROP DATABASE IF EXISTS MEMESTREAM;
CREATE DATABASE MEMESTREAM;

USE MEMESTREAM;

CREATE TABLE AGENT (

	Username VARCHAR(16) PRIMARY KEY NOT NULL UNIQUE,
    Pass VARCHAR(32) NOT NULL
    
);


CREATE TABLE POST (

	Title VARCHAR(32) PRIMARY KEY NOT NULL UNIQUE
    
);

CREATE TABLE POST_RATING (

	AgentUsername VARCHAR(16) NOT NULL,
    PostTitle VARCHAR(32) NOT NULL,
    Rating INT NOT NULL CHECK(Rating = -1 OR Rating = 1),
    
    PRIMARY KEY (AgentUsername, PostTitle),
    FOREIGN KEY (AgentUsername) REFERENCES AGENT (Username),
    FOREIGN KEY (PostTitle) REFERENCES POST (Title)
    
);